[package]
name = "clade"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
arrow-flight = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = "0.12"
