[package]
name = "seafowl"
build = "build.rs"
version = "0.1.0"
edition = "2021"

[features]
catalog-postgres = ["sqlx/postgres"]
default = ["catalog-postgres", "frontend-postgres", "object-store-s3"]
frontend-postgres = ["convergence", "convergence-arrow"]
object-store-s3 = ["object_store/aws"]

[dependencies]
arrow = { version = "20.0.0", features = ["prettyprint"] }
async-trait = "0.1.41"
base64 = "0.13.0"

bytes = "1.1.0"
clap = { version = "3.2.15", features = [ "derive" ] }
config = "0.13.1"

# PG wire protocol support
convergence = { git = "https://github.com/returnString/convergence", rev = "d78220e5a851d54385050e29adae69935955dc4f", optional = true }
convergence-arrow = { git = "https://github.com/returnString/convergence", rev = "d78220e5a851d54385050e29adae69935955dc4f", package = "convergence-arrow", optional = true }
datafusion = "11"
futures = "0.3"

# passing to DF's query planner
hashbrown = { version = "0.12", features = ["raw"] }
hex = ">=0.4.0"
itertools = ">=0.10.0"
log = "0.4"
object_store = ">=0.4.0"
pretty_env_logger = "0.4"

# Needs to be in non-dev because repository::testutils can't be
# imported by tests::end_to_end if it's cfg(test).
rand = "0.8"
serde = "1.0.138"
serde_json = "1.0.81"
sha2 = ">=0.10.1"
sqlparser = "0.20"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }
strum = ">=0.24"
strum_macros = ">=0.24"
tempfile = "3"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
url = "2.2"
warp = "0.3"

# For WASM user-defined functions
wasmtime = "0.38.1"

[dev-dependencies]
mockall = "0.11.1"
test-case = "*"

[build-dependencies]
anyhow = "1.0.60"  # for build.rs
vergen = "7"
