# Default config for dev

[object_store]
type = "local"
data_dir = "../seafowl-data"

[catalog]
type = "sqlite"
dsn = "../seafowl-data/seafowl.sqlite"

[frontend.postgres]
bind_port = 6432

[frontend.http]
bind_host = "0.0.0.0"
write_access = "8c0754add53c7ef2781fba551fa8427bbedb251d03ea9685402ba3126c746ac5"
