name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  CI:
    name: Lint, build, test
    runs-on: ubuntu-latest
    env:
      # set debuginfo to 1 (line tables only, for panic tracebacks)
      RUSTFLAGS: "-C debuginfo=1"

    steps:
      - uses: actions/checkout@v4

      - name: Code format check
        run: |
          rustup component add rustfmt 
          cargo fmt --all --check

      - name: .toml file format check
        run: |
          cargo install taplo-cli --locked
          taplo fmt --check

      - name: Install protoc
        run: |
          mkdir -p $HOME/d/protoc
          cd $HOME/d/protoc
          export PROTO_ZIP="protoc-21.4-linux-x86_64.zip"
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.4/$PROTO_ZIP
          unzip $PROTO_ZIP
          echo "$HOME/d/protoc/bin" >> $GITHUB_PATH
          export PATH=$PATH:$HOME/d/protoc/bin
          protoc --version

      - name: Build workspace in debug mode
        run: |
          cargo build

      - name: Clippy check
        run: |
          cargo clippy --all-targets --workspace --fix --allow-dirty --allow-staged --allow-no-vcs
          cargo clippy --all-targets --workspace -- -D warnings --allow clippy::needless_return  # remove once 13458 is resolved

      - name: Spin up the test object stores and postgres catalog
        run: docker compose up -d --wait || true

      # TODO split tests into unit and integration (one requires postgres?)
      - name: Run tests
        run: |
          cargo test --workspace
        env:
          DATABASE_URL: "postgres://postgres:test@localhost:5432/db_test"